### ISSUE TITLE
Ensure mounting of XXX filesystems is disabled check maybe wrong

### ISSUE THREAD

**Issue by arvatoth-vcc** [ansible-lockdown/UBUNTU20-CIS-Audit#16]
**Question**
Hi,

In `section_1/cis_1.1/cis_1.1.1.1_7.yml` file all `modprobe` command contains `jffs` instead of proper module name.

```
  cramfs:
    title: 1.1.1.1 | Ensure mounting of cramfs filesystems is disabled
    exit-status: 0
    exec: if [ `lsmod | grep -c cramfs` != 0 ]; then  "modprobe -n -v jffs | grep -E '(cramfs|install)'"; else echo OK; fi

  freevxfs:
    title: 1.1.1.2 | Ensure mounting of freevxfs filesystems is disabled
    exit-status: 0
    exec: if [ `lsmod | grep -c freevxfs` != 0 ]; then  "modprobe -n -v jffs | grep -E '(freevxfs|install)'"; else echo OK; fi

...
and other
```

I have opened only question instead of bug ticket, because I'm not entirely sure is this a bug or not.

**Environment (please complete the following information):**

- goss version: v0.3.18
- OS version: Ubuntu 20.04
